import { Team } from './types'

export const data: Team[] = [
  {
    id: '1',
    accountName: 'John Doe',
    email: 'john.doe@alertgroup.com.ng',
    role: 'Developer',
    twoFactorAuthEnabled: true,
    dateJoined: '2023-01-15T00:00:00.000Z',
  },
  {
    id: '2',
    accountName: 'Jane Smith',
    email: 'jane.smith@alertgroup.com.ng',
    role: 'Product Manager',
    twoFactorAuthEnabled: false,
    dateJoined: '2022-07-10T00:00:00.000Z',
  },
  {
    id: '3',
    accountName: 'Alice Brown',
    email: 'alice.brown@alertgroup.com.ng',
    role: 'Designer',
    twoFactorAuthEnabled: true,
    dateJoined: '2021-05-20T00:00:00.000Z',
  },
  {
    id: '4',
    accountName: 'Bob Johnson',
    email: 'bob.johnson@alertgroup.com.ng',
    role: 'DevOps Engineer',
    twoFactorAuthEnabled: false,
    dateJoined: '2020-11-30T00:00:00.000Z',
  },
  {
    id: '5',
    accountName: 'Chris Green',
    email: 'chris.green@alertgroup.com.ng',
    role: 'QA Engineer',
    twoFactorAuthEnabled: true,
    dateJoined: '2023-04-02T00:00:00.000Z',
  },
  {
    id: '6',
    accountName: 'Emily White',
    email: 'emily.white@alertgroup.com.ng',
    role: 'Scrum Master',
    twoFactorAuthEnabled: true,
    dateJoined: '2022-09-21T00:00:00.000Z',
  },
  {
    id: '7',
    accountName: 'David Black',
    email: 'david.black@alertgroup.com.ng',
    role: 'Frontend Developer',
    twoFactorAuthEnabled: false,
    dateJoined: '2021-12-15T00:00:00.000Z',
  },
  {
    id: '8',
    accountName: 'Laura King',
    email: 'laura.king@alertgroup.com.ng',
    role: 'Backend Developer',
    twoFactorAuthEnabled: true,
    dateJoined: '2020-06-10T00:00:00.000Z',
  },
  {
    id: '9',
    accountName: 'Michael Scott',
    email: 'michael.scott@alertgroup.com.ng',
    role: 'Business Analyst',
    twoFactorAuthEnabled: true,
    dateJoined: '2019-10-25T00:00:00.000Z',
  },
  {
    id: '10',
    accountName: 'Sara Lee',
    email: 'sara.lee@alertgroup.com.ng',
    role: 'UX Researcher',
    twoFactorAuthEnabled: false,
    dateJoined: '2021-03-14T00:00:00.000Z',
  },
]
